# -*- coding: utf-8 -*-
"""notebook7a89923157.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FqSjmZB3x1Uiqc5MJbGR9gsYe_jTy4WD
"""

# -*- coding: utf-8 -*-
"""notebookd6338ee69d.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fLMcG0PEEUyjMx2LxXL8TjuauFFxyYO_
"""

import numpy as np
import pandas as pd
from PIL import Image
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
import torch
import torch.optim as optim
from pathlib import Path
import cv2
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset
from torchvision import transforms
from tqdm.auto import tqdm
import matplotlib.pyplot as plt
from torch.optim.lr_scheduler import ReduceLROnPlateau

dir = Path("/kaggle/input/datasets/gpiosenka/sports-classification")
for subdirectories in dir.iterdir():
    train_path = dir / "train"
    test_path = dir / "test"
    val_path = dir / "valid"

csv_path = dir / "sports.csv"
df = pd.read_csv(csv_path)
df.head(200)
df.drop(columns = ['labels'])

train_df = df[df['data set'] == 'train'].drop(columns=['data set', 'labels'])
test_df = df[df['data set'] == 'test'].drop(columns=['data set', 'labels'])
val_df = df[df['data set'] == 'valid'].drop(columns=['data set', 'labels'])

train_df["filepaths"] = train_df["filepaths"].apply(lambda f: str(Path(dir) / f))
test_df["filepaths"] = test_df["filepaths"].apply(lambda f: str(Path(dir) / f))
val_df["filepaths"] = val_df["filepaths"].apply(lambda f: str(Path(dir) / f))

valid_ext = {"jpg", "jpeg"}

train_mask = (
    train_df["filepaths"]
    .astype(str)
    .str.rsplit(".", n=1)
    .str[-1]
    .str.lower()
    .isin(valid_ext)
)

val_mask = (
    val_df["filepaths"]
    .astype(str)
    .str.rsplit(".", n=1)
    .str[-1]
    .str.lower()
    .isin(valid_ext)
)

test_mask = (
    test_df["filepaths"]
    .astype(str)
    .str.rsplit(".", n=1)
    .str[-1]
    .str.lower()
    .isin(valid_ext)
)

train_df = train_df[train_mask].reset_index(drop=True)
test_df = test_df[test_mask].reset_index(drop=True)
val_df = val_df[val_mask].reset_index(drop=True)

train_transforms = transforms.Compose([
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomApply([
        transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2, hue=0.05)], p = 0.5
    ),
    transforms.ToTensor(),
])

eval_transforms = transforms.Compose([
    transforms.ToTensor()
])

class CustomDataset(Dataset):

    def __init__(self, features, labels, transform):
        self.labels = labels
        self.features = features
        self.transform = transform

    def __len__(self):
        return len(self.features)

    def __getitem__(self, idx):
        if self.features.iloc[idx].rsplit(".", 1)[-1].lower() not in {"jpeg", "jpg"}:
            raise ValueError("Non jpeg or jpg file")
        img = Image.open(self.features.iloc[idx]).convert("RGB")
        img = self.transform(img)
        return img, torch.tensor(self.labels.iloc[idx], dtype = torch.long)

train_dataset = CustomDataset(train_df['filepaths'], train_df['class id'], train_transforms)
test_dataset = CustomDataset(test_df['filepaths'], test_df['class id'], eval_transforms)
val_dataset = CustomDataset(val_df['filepaths'], val_df['class id'], eval_transforms)

train_dataset[200]

train_loader = DataLoader(train_dataset, shuffle=True, batch_size=8)
test_loader = DataLoader(test_dataset, shuffle=False, batch_size=8)
val_loader = DataLoader(val_dataset, shuffle=True, batch_size=8)

class resnetblock(nn.Module):

    def __init__(self, input_channels, output_channels, stride=1, identity_downsample=None):
        super().__init__()
        self.input_channels = input_channels
        self.output_channels = output_channels
        self.stride = stride
        self.identity_downsample = identity_downsample
        self.conv1 = nn.Conv2d(input_channels, output_channels, kernel_size=1, stride=1, padding=0)
        self.bn1 = nn.BatchNorm2d(output_channels)
        self.conv2 = nn.Conv2d(output_channels, output_channels, kernel_size=3, stride=stride, padding=1)
        self.bn2 = nn.BatchNorm2d(output_channels)
        self.conv3 = nn.Conv2d(output_channels, output_channels*4, kernel_size=1, stride=1, padding=0)
        self.bn3 = nn.BatchNorm2d(output_channels*4)
        self.relu = nn.ReLU()

    def forward(self, x):
        identity = x
        x = self.conv1(x)
        x = self.bn1(x)
        x = self.relu(x)
        x = self.conv2(x)
        x = self.bn2(x)
        x = self.relu(x)
        x = self.conv3(x)
        x = self.bn3(x)
        if self.identity_downsample is not None:
            identity = self.identity_downsample(identity)
        x = x + identity
        x = self.relu(x)
        return x


class resnet(nn.Module):

    def __init__(self, block, layers, num_of_classes, num_of_channels):
        super().__init__()
        self.block = block
        self.num_of_classes = num_of_classes
        self.num_of_channels = num_of_channels
        self.input_channels = 64
        self.conv1 = nn.Conv2d(self.num_of_channels, self.input_channels, kernel_size=7, stride=2, padding=3)
        self.bn1 = nn.BatchNorm2d(self.input_channels)
        self.relu = nn.ReLU()
        self.maxpool = nn.MaxPool2d(kernel_size=3, stride=2, padding=1)
        self.layer1 = self._make_layer(block, layers[0], 1, 64)
        self.layer2 = self._make_layer(block, layers[1], 2, 128)
        self.layer3 = self._make_layer(block, layers[2], 2, 256)
        self.layer4 = self._make_layer(block, layers[3], 2, 512)
        self.avgpool = nn.AdaptiveAvgPool2d((1, 1))
        self.fc = nn.Linear(2048, num_of_classes)
        self.dropout_fc = nn.Dropout(0.5)

    def _make_layer(self, block, num_of_blocks, stride, output_channel):
        layers = []
        identity_downsample = None
        if stride != 1 or self.input_channels != output_channel*4:
            identity_downsample = nn.Sequential(nn.Conv2d(self.input_channels, output_channel*4, kernel_size=1, stride=stride, padding=0),
                                               nn.BatchNorm2d(output_channel*4))
        layers.append(block(self.input_channels, output_channel, stride, identity_downsample))
        self.input_channels = output_channel*4
        for i in range(1, num_of_blocks):
            layers.append(block(self.input_channels, output_channel))
        return nn.Sequential(*layers)

    def forward(self, x):
        x = self.conv1(x)
        x = self.bn1(x)
        x = self.relu(x)
        x = self.maxpool(x)
        x = self.layer1(x)
        x = self.layer2(x)
        x = self.layer3(x)
        x = self.layer4(x)
        x = self.avgpool(x)
        x = torch.flatten(x, 1)
        x = self.dropout_fc(x)
        x = self.fc(x)
        return x

resnet101 = resnet(resnetblock, [3, 4, 23, 3], 100, 3)
optimizer = optim.Adam(resnet101.parameters(), lr = 0.0001, weight_decay = 1e-4)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
resnet101.to(device)

criterion = nn.CrossEntropyLoss()

from sklearn.metrics import f1_score

train_acc = []
val_acc = []
train_loss = []
val_loss = []
train_f1 = []
val_f1 = []

total_epochs = 50

for i in range(total_epochs):
    resnet101.train()
    all_pred = []
    all_true = []
    train_epoch_loss = 0.0
    correct = 0
    total_samples = 0
    num_batches = 0

    for batch_features, batch_labels in tqdm(train_loader, desc = f"Epoch: {i+1}"):
        batch_features = batch_features.to(device)
        batch_labels = batch_labels.to(device)

        optimizer.zero_grad()
        out = resnet101(batch_features)
        loss = criterion(out, batch_labels)
        loss.backward()
        optimizer.step()

        train_epoch_loss += loss.item()
        _, predicted = torch.max(out, 1)

        correct += (predicted == batch_labels).sum().item()
        total_samples += batch_labels.size(0)
        num_batches += 1

        all_pred.append(predicted.cpu())
        all_true.append(batch_labels.cpu())

    y_pred = torch.cat(all_pred).numpy()
    y_true = torch.cat(all_true).numpy()

    train_accuracy = 100 * (correct / total_samples)
    train_epoch_loss /= num_batches
    train_f1_score = f1_score(y_true, y_pred, average="macro")

    train_acc.append(train_accuracy)
    train_loss.append(train_epoch_loss)
    train_f1.append(train_f1_score)

    print("-" * 10)
    print(f"Epoch {i+1}")
    print(f"Train acc: {train_accuracy:.2f}")
    print(f"Train loss: {train_epoch_loss:.4f}")
    print(f"Train F1: {train_f1_score:.4f}")

    resnet101.eval()

    all_pred = []
    all_true = []
    val_loss_epoch = 0.0
    correct = 0
    total_samples_val = 0
    num_batches = 0

    with torch.no_grad():
        for batch_features, batch_labels in val_loader:
            batch_features = batch_features.to(device)
            batch_labels = batch_labels.to(device)

            out = resnet101(batch_features)
            loss = criterion(out, batch_labels)

            val_loss_epoch += loss.item()
            _, predicted = torch.max(out, 1)

            correct += (predicted == batch_labels).sum().item()
            total_samples_val += batch_labels.size(0)
            num_batches += 1

            all_pred.append(predicted.cpu())
            all_true.append(batch_labels.cpu())

    y_pred = torch.cat(all_pred).numpy()
    y_true = torch.cat(all_true).numpy()

    val_accuracy = 100 * correct / total_samples_val
    val_loss_epoch /= num_batches
    val_f1_score = f1_score(y_true, y_pred, average="macro")

    val_acc.append(val_accuracy)
    val_loss.append(val_loss_epoch)
    val_f1.append(val_f1_score)

    print("-" * 10)
    print(f"Epoch {i+1}")
    print(f"Val acc: {val_accuracy:.2f}")
    print(f"Val loss: {val_loss_epoch:.4f}")
    print(f"Val F1: {val_f1_score:.4f}")

epochs = range(1, total_epochs + 1)

# Accuracy
plt.figure()
plt.plot(epochs, train_acc, label="Train Accuracy")
plt.plot(epochs, val_acc, label="Val Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend()
plt.savefig("accuracy.png")
plt.close()

# Loss
plt.figure()
plt.plot(epochs, train_loss, label="Train Loss")
plt.plot(epochs, val_loss, label="Val Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.savefig("loss.png")
plt.close()

# F1 Score
plt.figure()
plt.plot(epochs, train_f1, label="Train F1")
plt.plot(epochs, val_f1, label="Val F1")
plt.xlabel("Epoch")
plt.ylabel("F1 Score")
plt.legend()
plt.savefig("f1_score.png")
plt.close()

from sklearn.metrics import f1_score

test_acc = 0.0
correct = 0
total_samples = 0
all_pred = []
all_true = []
y_pred = []
y_true = []

resnet101.eval()
with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        batch_features = batch_features.to(device)
        batch_labels = batch_labels.to(device)

        out = resnet101(batch_features)
        _, predicted = torch.max(out, 1)
        correct += (predicted == batch_labels).sum().item()
        total_samples += batch_labels.shape[0]
        all_pred.append(predicted.cpu())
        all_true.append(batch_labels.cpu())

y_pred = torch.cat(all_pred).numpy()
y_true = torch.cat(all_true).numpy()

test_acc = (correct / total_samples)*100

test_f1 = f1_score(y_true, y_pred, average="macro")

print(f"Test acc: {test_acc:.2f}")
print(f"Test F1: {test_f1:.4f}")

